### ISSUE TITLE
Limitiranje ka blic.rs ?

### ISSUE THREAD

**Issue by mokiding** [MihailoIsakov/sandwich-hunter#1]
Koliko sam skapirao http://COLLECTOR_URL/comment prima sledece POST val:
userid -> UserID autora komentara ?
id -> id komentar ?
link -> url ? blic.rs/komentar/blabla  ?
author-> Ime autora komentara ?
parent_author -> ????
comment -> komentar ?
vote_count -> ukupno glasova 
upvotes -> UpVote
downvotes ->DownVote
timestamp -> vreme kada je komentar okacen ? u timestamp formatu ?

Da li nam mozes reci sta predstavlja sta od podataka, da bih bila moguca integracija i drugih stranica poput alo.rs/kurir ...

**Comment by MihailoIsakov** [comment]
Eno ti access bekendu, nemam sad snage da kucam :D

**Comment by MihailoIsakov** [comment]
U principu sve je jasno kad otvoris neku Blic stranu,
id je id komentara,
link je link za stranicu na kojoj je korisnik trenutno (moze predstavljati problem buduci da mozes otvoriti i komentare za neki clanak, odvojeno od clanka, ali da se srediti),
author je ime autora komentara,
parend_author je ime komentatora na koji komentar odgovara, kao mention na twitteru,
comment je tekst komentara,
timestamp mislim da nisam vadio, ali postoji u htmlu kao tekst. zahtevace malo parsiranja, tako da mi nije hitno. 

Svakako planiram da uradim scrape celog blica pa cu pokupiti sta mi fali kasnije.
